/**
 * app.js — AL-HSI-SAM2 Liquid Galaxy Dashboard Controller
 *
 * Auto-loads real experiment data from /data/ JSONs generated by
 * scripts/generate_dashboard_data.py (run on Google Colab with GPU).
 * Falls back to high-quality synthetic demo data if files aren't present yet.
 *
 * Panels:
 *   1. False-color composite (PCA → RGB from real HSI cube)
 *   2. Segmentation map (real GT vs model predictions)
 *   3. Uncertainty heatmap (real BALD/entropy scores, inferno colormap)
 *   4. Query locations + multi-strategy annotation efficiency chart
 */

'use strict';

// ============================================================================
// Class definitions
// ============================================================================

const CLASS_COLORS_PV = [
    [20, 20, 30],       // 0: Background
    [220, 40, 40],      // 1: Asphalt
    [30, 180, 80],      // 2: Meadows
    [160, 140, 110],    // 3: Gravel
    [20, 120, 40],      // 4: Trees
    [100, 180, 200],    // 5: Painted Metal Sheets
    [160, 110, 60],     // 6: Bare Soil
    [80, 80, 160],      // 7: Bitumen
    [220, 100, 60],     // 8: Self-Blocking Bricks
    [60, 100, 160],     // 9: Shadows
];
const CLASS_NAMES_PV = [
    "Background", "Asphalt", "Meadows", "Gravel", "Trees",
    "Metal Sheets", "Bare Soil", "Bitumen", "Bricks", "Shadows",
];

const CLASS_COLORS_IP = [
    [20, 20, 30],
    [140, 67, 46], [0, 155, 60], [160, 220, 100], [30, 170, 60],
    [128, 128, 0], [34, 139, 34], [107, 142, 35], [210, 180, 140],
    [255, 80, 0], [184, 134, 11], [218, 165, 32], [189, 183, 107],
    [255, 215, 0], [85, 107, 47], [148, 103, 189], [112, 128, 144],
];
const CLASS_NAMES_IP = [
    "Background", "Alfalfa", "Corn-notill", "Corn-mintill", "Corn",
    "Grass-pasture", "Grass-trees", "Grass-mowed", "Hay-windrowed", "Oats",
    "Soybean-notill", "Soybean-mintill", "Soybean-clean", "Wheat", "Woods",
    "Bldg-Grass-Trees", "Stone-Steel",
];

// Round colors for query markers
const ROUND_COLORS = [
    "#6366f1", "#06b6d4", "#10b981", "#f59e0b", "#f43f5e",
    "#8b5cf6", "#ec4899", "#14b8a6", "#84cc16", "#f97316",
];

// Strategy line colors for chart
const STRATEGY_COLORS = {
    bald:    { line: "#6366f1", label: "BALD" },
    entropy: { line: "#06b6d4", label: "Entropy" },
    random:  { line: "#94a3b8", label: "Random" },
};

// ============================================================================
// Inferno colormap
// ============================================================================
function infernoColor(t) {
    t = Math.max(0, Math.min(1, t));
    const stops = [
        [0.00, 13,   8,  135],
        [0.13, 70,   3,  159],
        [0.25, 114,  1,  168],
        [0.38, 156, 23,  158],
        [0.50, 189, 55,  134],
        [0.63, 216, 87,  107],
        [0.75, 237, 121,  83],
        [0.88, 251, 159,  58],
        [1.00, 240, 249,  33],
    ];
    let lo = stops[0], hi = stops[stops.length - 1];
    for (let i = 0; i < stops.length - 1; i++) {
        if (t >= stops[i][0] && t <= stops[i + 1][0]) { lo = stops[i]; hi = stops[i + 1]; break; }
    }
    const f = (t - lo[0]) / (hi[0] - lo[0] + 1e-8);
    return [
        Math.round(lo[1] + f * (hi[1] - lo[1])),
        Math.round(lo[2] + f * (hi[2] - lo[2])),
        Math.round(lo[3] + f * (hi[3] - lo[3])),
    ];
}

// ============================================================================
// State
// ============================================================================
const state = {
    dataset:      "pavia",
    round:        0,
    maxRound:     10,
    strategy:     "bald",
    showGT:       true,
    playing:      false,
    playInterval: null,
    isRealData:   false,

    falseColor:   null,
    uncertainty:  null,
    segmentation: null,
    queryHistory: null,
    metrics:      null,   // { strategies: { bald: {rounds}, entropy: {rounds}, random: {rounds} }, initial }

    classColors:  CLASS_COLORS_PV,
    classNames:   CLASS_NAMES_PV,
};

// ============================================================================
// DOM refs
// ============================================================================
const $ = (sel) => document.querySelector(sel);

const canvasRGB      = $('#canvas-rgb');
const canvasSeg      = $('#canvas-seg');
const canvasUnc      = $('#canvas-uncertainty');
const canvasQueries  = $('#canvas-queries');
const chartCanvas    = $('#chart-efficiency');

const roundSlider    = $('#round-slider');
const roundDisplay   = $('#round-display');
const datasetSelect  = $('#dataset-select');
const strategySelect = $('#strategy-select');
const toggleGTBtn    = $('#toggle-gt');
const toggleGTLabel  = $('#toggle-gt-label');
const playBtn        = $('#play-btn');
const loadBtn        = $('#load-btn');
const statusText     = $('#status-text');
const statusDot      = $('#status-dot');
const pipsRow        = $('#timeline-pips');

// Panel status spans
const rgbStatus  = $('#rgb-status');
const segStatus  = $('#seg-status');
const uncStatus  = $('#unc-status');
const alStatus   = $('#al-status');

// ============================================================================
// Status helpers
// ============================================================================
function setStatus(msg, state_ = 'idle') {
    statusText.textContent = msg;
    statusDot.className = 'status-dot' + (state_ === 'idle' ? '' : ` ${state_}`);
}

function setPanelStatus(el, msg) { el.textContent = msg; }

// ============================================================================
// Build timeline pips
// ============================================================================
function buildPips(max) {
    pipsRow.innerHTML = '';
    for (let i = 0; i <= max; i++) {
        const pip = document.createElement('span');
        pip.className = 'timeline-pip' + (i <= state.round ? ' active' : '');
        pip.dataset.round = i;
        pip.title = `Round ${i}`;
        pip.addEventListener('click', () => { setRound(i); });
        pipsRow.appendChild(pip);
    }
}

function updatePips() {
    document.querySelectorAll('.timeline-pip').forEach(p => {
        p.classList.toggle('active', parseInt(p.dataset.round) <= state.round);
    });
    // Update slider gradient
    const pct = state.maxRound > 0 ? (state.round / state.maxRound) * 100 : 0;
    roundSlider.style.setProperty('--progress', `${pct}%`);
    roundDisplay.textContent = `${state.round} / ${state.maxRound}`;
}

function setRound(r) {
    state.round = Math.max(0, Math.min(r, state.maxRound));
    roundSlider.value = state.round;
    updatePips();
    renderSegmentation();
    renderQueryMap();
    renderEfficiencyChart();
    updateHeaderStats();
}

// ============================================================================
// Header stats updater
// ============================================================================
function updateHeaderStats() {
    const roundMetrics = getCurrentRoundMetrics();
    if (roundMetrics) {
        $('#hdr-miou').textContent = (roundMetrics.miou * 100).toFixed(2) + '%';
        const labeled_pct = state.metrics?.initial?.labeled_count
            ? ((roundMetrics.labeled_count / 42776) * 100).toFixed(1) + '%'
            : '—';
        $('#hdr-labels').textContent = labeled_pct;
    }
}

function getCurrentRoundMetrics() {
    if (!state.metrics) return null;

    // Handle multi-strategy format (real data)
    if (state.metrics.strategies) {
        const stratData = state.metrics.strategies[state.strategy];
        if (!stratData) return null;
        const rounds = stratData.rounds || [];
        if (state.round === 0) return state.metrics.initial || null;
        return rounds.find(r => r.round === state.round) || rounds[state.round - 1] || null;
    }

    // Handle single-strategy format (legacy/demo)
    if (state.metrics.rounds) {
        if (state.round === 0) return state.metrics.initial || null;
        return state.metrics.rounds[state.round - 1] || null;
    }
    return null;
}

// ============================================================================
// Rendering: False-Color
// ============================================================================
function renderFalseColor() {
    if (!state.falseColor) return;
    const { width, height, pixels } = state.falseColor;
    canvasRGB.width = width; canvasRGB.height = height;
    const ctx = canvasRGB.getContext('2d');
    const img = ctx.createImageData(width, height);

    for (let y = 0; y < height; y++) {
        for (let x = 0; x < width; x++) {
            const idx = (y * width + x) * 4;
            const px  = pixels[y][x];
            img.data[idx]     = Math.round(px[0]);
            img.data[idx + 1] = Math.round(px[1]);
            img.data[idx + 2] = Math.round(px[2]);
            img.data[idx + 3] = 255;
        }
    }
    ctx.putImageData(img, 0, 0);
    $('#stat-resolution').textContent = `${width} × ${height}`;
    setPanelStatus(rgbStatus, 'LIVE');
    rgbStatus.classList.add('active');
    $('#ph-rgb').classList.add('hidden');
}

// ============================================================================
// Rendering: Segmentation
// ============================================================================
function renderSegmentation() {
    if (!state.segmentation) return;
    const { width, height, ground_truth, predictions } = state.segmentation;
    canvasSeg.width = width; canvasSeg.height = height;
    const ctx = canvasSeg.getContext('2d');
    const img = ctx.createImageData(width, height);
    const src = state.showGT ? ground_truth : predictions;
    const colors = state.classColors;

    for (let y = 0; y < height; y++) {
        for (let x = 0; x < width; x++) {
            const idx = (y * width + x) * 4;
            const cls = src[y][x];
            const c   = colors[cls] || [50, 50, 60];
            img.data[idx]     = c[0];
            img.data[idx + 1] = c[1];
            img.data[idx + 2] = c[2];
            img.data[idx + 3] = 255;
        }
    }
    ctx.putImageData(img, 0, 0);

    // Metrics overlay
    const rd = getCurrentRoundMetrics();
    if (rd) {
        $('#stat-miou').textContent = `mIoU: ${(rd.miou * 100).toFixed(2)}%`;
        $('#stat-oa').textContent   = rd.overall_accuracy
            ? `OA: ${(rd.overall_accuracy * 100).toFixed(2)}%`
            : `Round ${state.round}`;
    }
    setPanelStatus(segStatus, 'LIVE');
    segStatus.classList.add('active');
    $('#ph-seg').classList.add('hidden');
}

// ============================================================================
// Rendering: Uncertainty Heatmap
// ============================================================================
function renderUncertainty() {
    if (!state.uncertainty) return;
    const { width, height, values } = state.uncertainty;
    canvasUnc.width = width; canvasUnc.height = height;
    const ctx = canvasUnc.getContext('2d');
    const img = ctx.createImageData(width, height);

    let sum = 0, maxV = 0;
    for (let y = 0; y < height; y++) {
        for (let x = 0; x < width; x++) {
            const idx = (y * width + x) * 4;
            const v   = values[y][x];
            const [r, g, b] = infernoColor(v);
            img.data[idx]     = r;
            img.data[idx + 1] = g;
            img.data[idx + 2] = b;
            img.data[idx + 3] = 255;
            sum += v; if (v > maxV) maxV = v;
        }
    }
    ctx.putImageData(img, 0, 0);
    const mean = sum / (width * height);
    $('#stat-mean-unc').textContent = `Mean: ${mean.toFixed(3)}`;
    $('#stat-max-unc').textContent  = `Max: ${maxV.toFixed(3)}`;

    const ucType = state.strategy === 'bald' ? 'BALD' : state.strategy === 'entropy' ? 'ENTROPY' : 'σ';
    $('#uncertainty-type').textContent = ucType;

    setPanelStatus(uncStatus, 'LIVE');
    uncStatus.classList.add('active');
    $('#ph-unc').classList.add('hidden');
}

// ============================================================================
// Rendering: Query Map
// ============================================================================
function renderQueryMap() {
    if (!state.falseColor || !state.queryHistory) return;
    const { width, height, pixels } = state.falseColor;
    canvasQueries.width = width; canvasQueries.height = height;
    const ctx = canvasQueries.getContext('2d');

    // Dimmed background
    const img = ctx.createImageData(width, height);
    for (let y = 0; y < height; y++) {
        for (let x = 0; x < width; x++) {
            const idx = (y * width + x) * 4;
            const px  = pixels[y][x];
            img.data[idx]     = Math.round(px[0] * 0.25);
            img.data[idx + 1] = Math.round(px[1] * 0.25);
            img.data[idx + 2] = Math.round(px[2] * 0.25);
            img.data[idx + 3] = 255;
        }
    }
    ctx.putImageData(img, 0, 0);

    // Query dots
    const numRounds = Math.min(state.round, state.queryHistory.length);
    for (let r = 0; r < numRounds; r++) {
        const rd = state.queryHistory[r];
        ctx.fillStyle = ROUND_COLORS[r % ROUND_COLORS.length];
        ctx.globalAlpha = 0.9;
        for (const coord of rd.coordinates) {
            const [row, col] = coord;
            ctx.beginPath();
            ctx.arc(col, row, 1.8, 0, Math.PI * 2);
            ctx.fill();
        }
    }
    ctx.globalAlpha = 1.0;

    // Labeled count
    const rd = getCurrentRoundMetrics();
    if (rd) {
        $('#stat-labeled').textContent  = `Labels: ${rd.labeled_count?.toLocaleString() || '—'}`;
        $('#stat-round-info').textContent = `Round: ${state.round} / ${state.maxRound}`;
    }

    setPanelStatus(alStatus, 'LIVE');
    alStatus.classList.add('active');
    $('#ph-queries').classList.add('hidden');
}

// ============================================================================
// Rendering: Annotation Efficiency Chart
// ============================================================================
function renderEfficiencyChart() {
    if (!state.metrics) return;
    const canvas = chartCanvas;
    const rect   = canvas.parentElement.getBoundingClientRect();
    canvas.width  = Math.max(100, rect.width);
    canvas.height = Math.max(60,  rect.height - 20);
    const ctx = canvas.getContext('2d');
    const W = canvas.width, H = canvas.height;
    const pad = { top: 16, right: 16, bottom: 30, left: 42 };
    const cW = W - pad.left - pad.right;
    const cH = H - pad.top - pad.bottom;

    ctx.clearRect(0, 0, W, H);

    // Collect all round data across strategies
    let allRounds = [];
    let allMious  = [];

    const strategyMap = {};
    if (state.metrics.strategies) {
        // Real data: multi-strategy
        Object.entries(state.metrics.strategies).forEach(([key, data]) => {
            const pts = (data.rounds || []).map(r => ({ x: r.labeled_count, y: r.miou }));
            strategyMap[key] = pts;
            pts.forEach(p => { allRounds.push(p.x); allMious.push(p.y); });
        });
    } else if (state.metrics.rounds) {
        // Demo / single-strategy
        const pts = state.metrics.rounds.map(r => ({ x: r.labeled_count, y: r.miou }));
        strategyMap[state.strategy] = pts;
        pts.forEach(p => { allRounds.push(p.x); allMious.push(p.y); });
    }

    if (allRounds.length === 0) return;

    const xMin = Math.min(...allRounds);
    const xMax = Math.max(...allRounds);
    const yMin = 0;
    const yMax = Math.min(1, Math.max(...allMious) * 1.15);

    const toX = v => pad.left + ((v - xMin) / (xMax - xMin + 1e-8)) * cW;
    const toY = v => pad.top  + (1 - (v - yMin) / (yMax - yMin + 1e-8)) * cH;

    // Grid lines
    ctx.strokeStyle = 'rgba(26,38,64,0.8)';
    ctx.lineWidth = 1;
    for (let i = 0; i <= 4; i++) {
        const y = pad.top + (cH / 4) * i;
        ctx.beginPath(); ctx.moveTo(pad.left, y); ctx.lineTo(W - pad.right, y); ctx.stroke();
        const val = yMax - (yMax / 4) * i;
        ctx.fillStyle = 'rgba(71,85,105,0.8)';
        ctx.font = '9px JetBrains Mono, monospace';
        ctx.textAlign = 'right';
        ctx.fillText((val * 100).toFixed(0) + '%', pad.left - 4, y + 3);
    }

    // Full supervision line
    const fsMiou = 0.8151;
    const fsY = toY(fsMiou);
    ctx.strokeStyle = 'rgba(100,116,139,0.4)'; ctx.lineWidth = 1;
    ctx.setLineDash([4, 4]);
    ctx.beginPath(); ctx.moveTo(pad.left, fsY); ctx.lineTo(W - pad.right, fsY); ctx.stroke();
    ctx.setLineDash([]);
    ctx.fillStyle = 'rgba(100,116,139,0.7)';
    ctx.font = '8px JetBrains Mono, monospace'; ctx.textAlign = 'right';
    ctx.fillText('Full sup.', W - pad.right, fsY - 3);

    // Draw lines for each strategy
    Object.entries(strategyMap).forEach(([key, pts]) => {
        if (pts.length === 0) return;
        const conf = STRATEGY_COLORS[key] || { line: '#888', label: key };

        // Line
        ctx.strokeStyle = conf.line; ctx.lineWidth = 2; ctx.globalAlpha = 0.9;
        ctx.beginPath();
        pts.forEach((p, i) => {
            const x = toX(p.x), y = toY(p.y);
            i === 0 ? ctx.moveTo(x, y) : ctx.lineTo(x, y);
        });
        ctx.stroke();

        // Dots
        ctx.fillStyle = conf.line; ctx.globalAlpha = 1;
        pts.forEach((p, i) => {
            const x = toX(p.x), y = toY(p.y);
            const isCurrentRound = (i + 1) === state.round;
            ctx.beginPath();
            ctx.arc(x, y, isCurrentRound ? 5 : 3, 0, Math.PI * 2);
            ctx.fill();
            if (isCurrentRound) {
                ctx.strokeStyle = 'white'; ctx.lineWidth = 1.5;
                ctx.beginPath(); ctx.arc(x, y, 5, 0, Math.PI * 2); ctx.stroke();
                ctx.lineWidth = 2;
            }
        });
        ctx.globalAlpha = 1;

        // Label at end of line
        if (pts.length > 0) {
            const last = pts[pts.length - 1];
            ctx.fillStyle = conf.line;
            ctx.font = 'bold 9px JetBrains Mono, monospace'; ctx.textAlign = 'left';
            ctx.fillText(conf.label, toX(last.x) + 4, toY(last.y) + 3);
        }
    });

    // X-axis label
    ctx.fillStyle = 'rgba(71,85,105,0.8)';
    ctx.font = '9px JetBrains Mono, monospace'; ctx.textAlign = 'center';
    ctx.fillText('Labeled Pixels', pad.left + cW / 2, H - 2);

    // Advantage annotation
    const baldRounds  = strategyMap['bald']    || [];
    const randRounds  = strategyMap['random']  || [];
    const entRounds   = strategyMap['entropy'] || [];
    const bestActive  = [...baldRounds, ...entRounds].filter(p => p.y > 0);
    const worstRand   = randRounds.filter(p => p.y > 0);
    if (bestActive.length && worstRand.length && state.round > 0) {
        const ri = Math.min(state.round - 1, bestActive.length - 1);
        const ri2= Math.min(state.round - 1, worstRand.length - 1);
        const adv = bestActive[ri].y - worstRand[ri2].y;
        if (adv > 0) {
            $('#stat-advantage').textContent = `+${(adv * 100).toFixed(1)}% vs Random`;
        }
    }
}

// ============================================================================
// Render All Panels
// ============================================================================
function renderAll() {
    renderFalseColor();
    renderSegmentation();
    renderUncertainty();
    renderQueryMap();
    renderEfficiencyChart();
    renderLegend();
    buildPips(state.maxRound);
    updatePips();
    updateHeaderStats();
}

// ============================================================================
// Legend
// ============================================================================
function renderLegend() {
    const container = $('#legend-items');
    container.innerHTML = '';
    state.classNames.forEach((name, i) => {
        if (i === 0) return; // skip background
        const c = state.classColors[i] || [80, 80, 80];
        const item = document.createElement('div');
        item.className = 'legend-item';
        item.innerHTML = `
            <span class="legend-swatch" style="background:rgb(${c[0]},${c[1]},${c[2]})"></span>
            <span class="legend-label">${name}</span>
        `;
        container.appendChild(item);
    });
}

// ============================================================================
// Demo Data Generator (high quality fallback)
// ============================================================================
function mulberry32(seed) {
    return function () {
        seed |= 0; seed = seed + 0x6D2B79F5 | 0;
        let t = Math.imul(seed ^ seed >>> 15, 1 | seed);
        t = t + Math.imul(t ^ t >>> 7, 61 | t) ^ t;
        return ((t ^ t >>> 14) >>> 0) / 4294967296;
    };
}
function clamp(v, lo, hi) { return Math.max(lo, Math.min(hi, v)); }

function generateDemoData(dataset = "pavia") {
    const W = dataset === 'pavia' ? 170 : 145;
    const H = dataset === 'pavia' ? 100 : 145;
    const numClasses = dataset === 'pavia' ? 10 : 17;
    const numRounds  = 10;

    state.classColors = dataset === 'pavia' ? CLASS_COLORS_PV : CLASS_COLORS_IP;
    state.classNames  = dataset === 'pavia' ? CLASS_NAMES_PV  : CLASS_NAMES_IP;

    const rng = mulberry32(42);

    // Voronoi seeds
    const seeds = Array.from({ length: numClasses }, (_, c) => ({
        x: Math.floor(rng() * W), y: Math.floor(rng() * H), cls: c,
    }));

    const pixels = [], gt = [], pred = [], unc = [];

    for (let y = 0; y < H; y++) {
        const rPx = [], rGt = [], rPred = [], rUnc = [];
        for (let x = 0; x < W; x++) {
            let minD = Infinity, cls = 0;
            for (const s of seeds) {
                const d = Math.hypot(x - s.x, y - s.y);
                if (d < minD) { minD = d; cls = s.cls; }
            }
            const base = state.classColors[cls] || [100, 100, 100];
            rPx.push([
                clamp(base[0] + (rng() - 0.5) * 50, 0, 255),
                clamp(base[1] + (rng() - 0.5) * 50, 0, 255),
                clamp(base[2] + (rng() - 0.5) * 50, 0, 255),
            ]);
            rGt.push(cls);
            rPred.push(minD < 4 || rng() > 0.88 ? Math.floor(rng() * numClasses) : cls);
            rUnc.push(Math.exp(-minD / 7) * 0.85 + rng() * 0.15);
        }
        pixels.push(rPx); gt.push(rGt); pred.push(rPred); unc.push(rUnc);
    }

    state.falseColor   = { width: W, height: H, pixels };
    state.segmentation = { width: W, height: H, ground_truth: gt, predictions: pred };
    state.uncertainty  = { width: W, height: H, values: unc, min_raw: 0, max_raw: 1 };

    // Realistic query history (biased toward class boundaries)
    const queryHistory = [];
    for (let r = 1; r <= numRounds; r++) {
        const coords = [];
        const n = 20 + Math.floor(rng() * 30);
        for (let q = 0; q < n; q++) {
            let bx = 0, by = 0, bUnc = -1;
            for (let a = 0; a < 6; a++) {
                const cx = Math.floor(rng() * W), cy = Math.floor(rng() * H);
                if (unc[cy][cx] > bUnc) { bUnc = unc[cy][cx]; bx = cx; by = cy; }
            }
            coords.push([by, bx]);
        }
        queryHistory.push({ round: r, coordinates: coords, num_new: coords.length });
    }
    state.queryHistory = queryHistory;

    // Realistic metrics matching our actual results (Pavia)
    const realMiouBald    = [0.516, 0.527, 0.556, 0.593, 0.616, 0.635, 0.648, 0.681, 0.684, 0.683];
    const realMiouEnt     = [0.516, 0.523, 0.574, 0.617, 0.624, 0.640, 0.664, 0.644, 0.700, 0.747];
    const realMiouRandom  = [0.516, 0.524, 0.576, 0.634, 0.633, 0.668, 0.643, 0.652, 0.671, 0.659];
    const baseLabelCount  = 2138;

    const buildRounds = (miouArr) => miouArr.map((m, i) => ({
        round: i + 1,
        labeled_count: baseLabelCount + (i + 1) * 22,
        miou: m, overall_accuracy: m + 0.10,
        num_new_labels: 22,
        mean_entropy: 1.5 - 0.12 * i,
    }));

    state.metrics = {
        initial: { labeled_count: baseLabelCount, miou: 0.0073 },
        strategies: {
            bald:    { rounds: buildRounds(realMiouBald),   strategy: 'bald'    },
            entropy: { rounds: buildRounds(realMiouEnt),    strategy: 'entropy' },
            random:  { rounds: buildRounds(realMiouRandom), strategy: 'random'  },
        },
    };

    state.maxRound = numRounds;
    roundSlider.max = numRounds;
    state.isRealData = false;
}

// ============================================================================
// Data Loading — tries real JSON first, falls back to demo
// ============================================================================
async function loadData() {
    setStatus('Loading data…', 'loading');

    try {
        const dir = 'data/';
        const [fcRes, uncRes, segRes, qhRes, metRes] = await Promise.all([
            fetch(dir + 'false_color.json'),
            fetch(dir + 'uncertainty_map.json'),
            fetch(dir + 'segmentation_map.json'),
            fetch(dir + 'query_history.json'),
            fetch(dir + 'metrics_summary.json'),
        ]);

        if (fcRes.ok && uncRes.ok && segRes.ok && qhRes.ok && metRes.ok) {
            state.falseColor   = await fcRes.json();
            state.uncertainty  = await uncRes.json();
            state.segmentation = await segRes.json();
            state.queryHistory = await qhRes.json();
            state.metrics      = await metRes.json();

            state.maxRound = state.queryHistory.length;
            roundSlider.max = state.maxRound;

            // Set class colors based on loaded dataset
            state.classColors = state.dataset === 'pavia' ? CLASS_COLORS_PV : CLASS_COLORS_IP;
            state.classNames  = state.dataset === 'pavia' ? CLASS_NAMES_PV  : CLASS_NAMES_IP;

            state.isRealData = true;
            setStatus('✅ Real experiment data loaded — Pavia University', 'ready');
        } else {
            throw new Error('Missing one or more data files');
        }
    } catch (e) {
        // Fall back to high-quality demo with real numbers
        generateDemoData(state.dataset);
        setStatus(
            '⚠️ Real data not found — showing demo with actual result numbers. Run scripts/generate_dashboard_data.py on Colab to load real data.',
            'idle'
        );
    }

    renderAll();
    buildPips(state.maxRound);
    state.round = Math.min(state.round, state.maxRound);
    updatePips();
}

// ============================================================================
// Event Listeners
// ============================================================================

// Round slider
roundSlider.addEventListener('input', () => {
    setRound(parseInt(roundSlider.value));
});

// Dataset change
datasetSelect.addEventListener('change', () => {
    state.dataset = datasetSelect.value;
    // Update class info
    state.classColors = state.dataset === 'pavia' ? CLASS_COLORS_PV : CLASS_COLORS_IP;
    state.classNames  = state.dataset === 'pavia' ? CLASS_NAMES_PV  : CLASS_NAMES_IP;
    if (!state.isRealData) {
        generateDemoData(state.dataset);
        renderAll();
    }
});

// Strategy change
strategySelect.addEventListener('change', () => {
    state.strategy = strategySelect.value;
    $('#uncertainty-type').textContent = state.strategy === 'bald' ? 'BALD' : state.strategy === 'entropy' ? 'ENTROPY' : 'σ';
    renderEfficiencyChart();
    updateHeaderStats();
});

// GT / Pred toggle
toggleGTBtn.addEventListener('click', () => {
    state.showGT = !state.showGT;
    toggleGTBtn.classList.toggle('active', state.showGT);
    toggleGTLabel.textContent = state.showGT ? 'GT' : 'PRED';
    renderSegmentation();
});

// Legend toggle on panel header click
$('#panel-seg .lg-panel__header').addEventListener('click', () => {
    $('#legend-float').classList.toggle('visible');
});

// Play
playBtn.addEventListener('click', () => {
    if (state.playing) {
        clearInterval(state.playInterval);
        state.playing = false;
        playBtn.classList.remove('playing');
        playBtn.innerHTML = '<svg width="14" height="14" viewBox="0 0 16 16" fill="currentColor"><polygon points="3,1 13,8 3,15"/></svg>';
    } else {
        state.playing = true;
        playBtn.classList.add('playing');
        playBtn.innerHTML = '<svg width="14" height="14" viewBox="0 0 16 16" fill="currentColor"><rect x="3" y="2" width="4" height="12"/><rect x="9" y="2" width="4" height="12"/></svg>';
        state.playInterval = setInterval(() => {
            const next = (state.round + 1) % (state.maxRound + 1);
            setRound(next);
            if (next === 0) {
                clearInterval(state.playInterval);
                state.playing = false;
                playBtn.classList.remove('playing');
                playBtn.innerHTML = '<svg width="14" height="14" viewBox="0 0 16 16" fill="currentColor"><polygon points="3,1 13,8 3,15"/></svg>';
            }
        }, 1200);
    }
});

// Load button
loadBtn.addEventListener('click', () => loadData());

// Resize
let resizeTimer;
window.addEventListener('resize', () => {
    clearTimeout(resizeTimer);
    resizeTimer = setTimeout(() => renderEfficiencyChart(), 150);
});

// ============================================================================
// Auto-load on DOMContentLoaded
// ============================================================================
document.addEventListener('DOMContentLoaded', () => {
    toggleGTBtn.classList.add('active');
    buildPips(10);
    // Auto-load data immediately
    loadData();
});
